version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    versioning-strategy: increase-if-necessary
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 21
    open-pull-requests-limit: 3
    groups:
      bundler:
        patterns:
          - "*"
    assignees:
      - "epistrephein"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
    assignees:
      - "epistrephein"
